"""Initial schema

Revision ID: 60bd9928f1ab
Revises:
Create Date: 2026-03-04 19:24:59.697614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60bd9928f1ab"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibratable_pulses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("waveform_type", sa.String(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("amp", sa.Float(), nullable=False),
        sa.Column("phase", sa.Float(), nullable=False),
        sa.Column("drag", sa.Float(), nullable=False),
        sa.Column("rise", sa.Float(), nullable=False),
        sa.Column("amp_setup", sa.Float(), nullable=False),
        sa.Column("std_dev", sa.Float(), nullable=False),
        sa.Column("owner_uuid", sa.Uuid(), nullable=False),
        sa.Column("pulse_role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hardware_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("calibration_id", sa.String(), nullable=False),
        sa.Column("logical_connectivity", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qubits",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_key", sa.String(), nullable=False),
        sa.Column("mean_z_map_args", sa.Text(), nullable=False),
        sa.Column("discriminator_real", sa.Float(), nullable=False),
        sa.Column("discriminator_imag", sa.Float(), nullable=False),
        sa.Column("direct_x_pi", sa.Boolean(), nullable=False),
        sa.Column("phase_comp_x_pi_2", sa.Float(), nullable=False),
        sa.Column("hardware_model_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hardware_model_id"],
            ["hardware_models.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "cross_resonance_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("auxiliary_qubit", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "resonators",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("qubit_uuid"),
    )
    op.create_table(
        "zx_pi_4_comps",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("auxiliary_qubit", sa.Integer(), nullable=False),
        sa.Column("phase_comp_target_zx_pi_4", sa.Float(), nullable=False),
        sa.Column("pulse_zx_pi_4_target_rotary_amp", sa.Float(), nullable=True),
        sa.Column("precomp_active", sa.Boolean(), nullable=False),
        sa.Column("postcomp_active", sa.Boolean(), nullable=False),
        sa.Column("use_second_state", sa.Boolean(), nullable=False),
        sa.Column("use_rotary", sa.Boolean(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "physical_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("channel_kind", sa.String(), nullable=False),
        sa.Column("name_index", sa.Integer(), nullable=False),
        sa.Column("block_size", sa.Integer(), nullable=False),
        sa.Column("default_amplitude", sa.Integer(), nullable=False),
        sa.Column("switch_box", sa.String(), nullable=False),
        sa.Column("swap_readout_iq", sa.Boolean(), nullable=False),
        sa.Column("baseband_uuid", sa.Uuid(), nullable=False),
        sa.Column("baseband_frequency", sa.Float(), nullable=True),
        sa.Column("baseband_if_frequency", sa.Float(), nullable=True),
        sa.Column("iq_bias", sa.String(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.Column("resonator_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["resonator_uuid"],
            ["resonators.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("channel_role", sa.String(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("ss_active", sa.Boolean(), nullable=True),
        sa.Column("ss_delay", sa.Float(), nullable=True),
        sa.Column("fs_active", sa.Boolean(), nullable=True),
        sa.Column("fs_amp", sa.Float(), nullable=True),
        sa.Column("fs_phase", sa.Float(), nullable=True),
        sa.Column("acq_delay", sa.Float(), nullable=True),
        sa.Column("acq_width", sa.Float(), nullable=True),
        sa.Column("acq_sync", sa.Boolean(), nullable=True),
        sa.Column("acq_use_weights", sa.Boolean(), nullable=True),
        sa.Column("reset_delay", sa.Float(), nullable=True),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.Column("resonator_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["resonator_uuid"],
            ["resonators.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pulse_channels")
    op.drop_table("physical_channels")
    op.drop_table("zx_pi_4_comps")
    op.drop_table("resonators")
    op.drop_table("cross_resonance_channels")
    op.drop_table("qubits")
    op.drop_table("hardware_models")
    op.drop_table("calibratable_pulses")
    # ### end Alembic commands ###
