"""Initial schema

Revision ID: 8e4fea651781
Revises:
Create Date: 2026-03-04 13:58:38.346560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e4fea651781"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hardware_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("calibration_id", sa.String(), nullable=False),
        sa.Column("logical_connectivity", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qubits",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_key", sa.String(), nullable=False),
        sa.Column("mean_z_map_args", sa.Text(), nullable=False),
        sa.Column("discriminator_real", sa.Float(), nullable=False),
        sa.Column("discriminator_imag", sa.Float(), nullable=False),
        sa.Column("direct_x_pi", sa.Boolean(), nullable=False),
        sa.Column("hardware_model_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hardware_model_id"],
            ["hardware_models.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "cross_resonance_cancellation_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("auxiliary_qubit", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "cross_resonance_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("auxiliary_qubit", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "qubit_pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "resonators",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "drive_pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("qubit_pulse_channels_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_pulse_channels_uuid"],
            ["qubit_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "physical_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("channel_kind", sa.String(), nullable=False),
        sa.Column("name_index", sa.Integer(), nullable=False),
        sa.Column("block_size", sa.Integer(), nullable=False),
        sa.Column("default_amplitude", sa.Integer(), nullable=False),
        sa.Column("switch_box", sa.String(), nullable=False),
        sa.Column("swap_readout_iq", sa.Boolean(), nullable=False),
        sa.Column("qubit_uuid", sa.Uuid(), nullable=True),
        sa.Column("resonator_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["resonator_uuid"],
            ["resonators.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "qubit_pulse_channels_base",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("ss_active", sa.Boolean(), nullable=False),
        sa.Column("ss_delay", sa.Float(), nullable=False),
        sa.Column("fs_active", sa.Boolean(), nullable=False),
        sa.Column("fs_amp", sa.Float(), nullable=False),
        sa.Column("fs_phase", sa.Float(), nullable=False),
        sa.Column("qubit_pulse_channels_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_pulse_channels_uuid"],
            ["qubit_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "resonator_pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("resonator_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resonator_uuid"],
            ["resonators.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "acquire_pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("resonator_pulse_channels_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resonator_pulse_channels_uuid"],
            ["resonator_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "basebands",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("if_frequency", sa.Float(), nullable=True),
        sa.Column("physical_channel_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["physical_channel_uuid"],
            ["physical_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "iq_voltage_biases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bias", sa.String(), nullable=False),
        sa.Column("physical_channel_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["physical_channel_uuid"],
            ["physical_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measure_pulse_channels",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=False),
        sa.Column("phase_iq_offset", sa.Float(), nullable=False),
        sa.Column("scale_real", sa.Float(), nullable=False),
        sa.Column("scale_imag", sa.Float(), nullable=False),
        sa.Column("resonator_pulse_channels_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resonator_pulse_channels_uuid"],
            ["resonator_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "calibratable_acquires",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("delay", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("sync", sa.Boolean(), nullable=False),
        sa.Column("use_weights", sa.Boolean(), nullable=False),
        sa.Column("acquire_pulse_channel_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquire_pulse_channel_uuid"],
            ["acquire_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calibratable_pulses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("waveform_type", sa.String(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("amp", sa.Float(), nullable=False),
        sa.Column("phase", sa.Float(), nullable=False),
        sa.Column("drag", sa.Float(), nullable=False),
        sa.Column("rise", sa.Float(), nullable=False),
        sa.Column("amp_setup", sa.Float(), nullable=False),
        sa.Column("std_dev", sa.Float(), nullable=False),
        sa.Column("drive_pulse_channel_uuid", sa.Uuid(), nullable=True),
        sa.Column("drive_pulse_channel_pulse_x_pi_uuid", sa.Uuid(), nullable=True),
        sa.Column("cr_channel_uuid", sa.Uuid(), nullable=True),
        sa.Column("measure_pulse_channel_uuid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cr_channel_uuid"],
            ["cross_resonance_channels.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["drive_pulse_channel_pulse_x_pi_uuid"],
            ["drive_pulse_channels.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["drive_pulse_channel_uuid"],
            ["drive_pulse_channels.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["measure_pulse_channel_uuid"],
            ["measure_pulse_channels.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calibratable_pulses")
    op.drop_table("calibratable_acquires")
    op.drop_table("measure_pulse_channels")
    op.drop_table("iq_voltage_biases")
    op.drop_table("basebands")
    op.drop_table("acquire_pulse_channels")
    op.drop_table("resonator_pulse_channels")
    op.drop_table("qubit_pulse_channels_base")
    op.drop_table("physical_channels")
    op.drop_table("drive_pulse_channels")
    op.drop_table("resonators")
    op.drop_table("qubit_pulse_channels")
    op.drop_table("cross_resonance_channels")
    op.drop_table("cross_resonance_cancellation_channels")
    op.drop_table("qubits")
    op.drop_table("hardware_models")
    # ### end Alembic commands ###
