"""Convert field to JSON

Revision ID: ed781b47f7d6
Revises: c14a89a58ae3
Create Date: 2026-03-04 15:43:47.812869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed781b47f7d6"
down_revision: Union[str, Sequence[str], None] = "c14a89a58ae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hardware_models", schema=None) as batch_op:
        batch_op.alter_column("logical_connectivity", existing_type=sa.TEXT(), type_=sa.JSON(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hardware_models", schema=None) as batch_op:
        batch_op.alter_column("logical_connectivity", existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=False)

    # ### end Alembic commands ###
